/* Automatically generated by po2tbl.sed from pybliographer.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"warning: can't import %s: %s", 2},
  {"value of `%s' should be of type %s", 3},
  {"String", 4},
  {"Boolean", 5},
  {"Integer", 6},
  {"Integer under %d", 7},
  {"Integer over %d", 8},
  {"Integer between %d and %d", 9},
  {"Element in `%s'", 10},
  {"Tuple (%s)", 11},
  {"List (%s)", 12},
  {"Dictionnary (%s, %s)", 13},
  {"Illegal year value", 14},
  {"Illegal month value", 15},
  {"Illegal day value", 16},
  {"in %s", 17},
  {"no input pipe `%s'", 18},
  {"no output pipe `%s'", 19},
  {"method `%s' provides no opener", 20},
  {"File `%s' does not exist", 21},
  {"don't know how to open `%s'", 22},
  {"method `%s' provides no iterator", 23},
  {"key `%s' is malformed", 24},
  {"%s:%d: key `%s' already defined", 25},
  {"Format entries", 26},
  {"Bibliography style:", 27},
  {"Select style", 28},
  {"Output format:", 29},
  {"Output File:", 30},
  {"Select output file", 31},
  {"Last Name, First Name", 32},
  {"Text", 33},
  {"Reference", 34},
  {"Day", 35},
  {"Month", 36},
  {"Year", 37},
  {"Invalid day field in date", 38},
  {"Invalid month field in date", 39},
  {"Invalid year field in date", 40},
  {"Entry type", 41},
  {"Key", 42},
  {"Create Field", 43},
  {"Mandatory", 44},
  {"Optional", 45},
  {"Extra", 46},
  {"Invalid key format", 47},
  {"Key `%s' already exists", 48},
  {"Error in native string parsing", 49},
  {"Edit entry", 50},
  {"Native Editing", 51},
  {"Standard Editing", 52},
  {"File", 53},
  {"Bibliography type:", 54},
  {"Add...", 55},
  {"Edit...", 56},
  {"Delete", 57},
  {"Search", 58},
  {"Field", 59},
  {"Pattern", 60},
  {"Simple Search", 61},
  {"Search command:", 62},
  {"Expert Search", 63},
  {"Full database", 64},
  {"internal error during evaluation", 65},
  {"\
while compiling %s\n\
error: %s", 66},
  {"Select sort criterions", 67},
  {"In use", 68},
  {"Sort criterions", 69},
  {"[Entry Type]", 70},
  {"[Key Value]", 71},
  {"Reorder", 72},
  {"Unselect all", 73},
  {"Yes", 74},
  {"\
The following errors occured:\n\
\n", 75},
  {"New", 76},
  {"Merge with...", 77},
  {"Previous Documents", 78},
  {"About...", 79},
  {"Submit a Bug Report", 80},
  {"Sort...", 81},
  {"Cite", 82},
  {"Format...", 83},
  {"Fields...", 84},
  {"Entries...", 85},
  {"Edit", 86},
  {"Settings", 87},
  {"Help", 88},
  {"Open", 89},
  {"Save", 90},
  {"Find", 91},
  {"Close", 92},
  {"\
can't open file `%s' for writing:\n\
%s", 93},
  {"New database", 94},
  {"[no entry]", 95},
  {"[1 entry]", 96},
  {"[%d entries]", 97},
  {"[%d/1 entry]", 98},
  {"[%d/%d entries]", 99},
  {"[modified]", 100},
  {"\
The database has been modified.\n\
Discard changes ?", 101},
  {"Merge file", 102},
  {"Open error", 103},
  {"Merge status", 104},
  {"Open file", 105},
  {"\
Unable to save `%s':\n\
%s", 106},
  {"\
An internal error occured during saving\n\
Try to Save As...", 107},
  {"\
The file `%s' already exists.\n\
Overwrite it ?", 108},
  {"\
During opening:\n\
%s", 109},
  {"\
An entry called `%s' already exists.\n\
Rename and add it anyway ?", 110},
  {"Really remove all the entries ?", 111},
  {"Really edit %d entries ?", 112},
  {"Remove all the %d entries ?", 113},
  {"Remove entry `%s' ?", 114},
  {"\
Can't connect to LyX:\n\
%s", 115},
  {"\
Please install bug-buddy\n\
to use this feature", 116},
  {"This program is copyrighted under the GNU GPL", 117},
  {"Gnome interface to the Pybliographer system.", 118},
  {"Pybliographer Home Page", 119},
  {"This is %s, version %s", 120},
  {"This is free software with ABSOLUTELY NO WARRANTY.", 121},
  {"For details, type `warranty'.", 122},
  {"%s: error: can't open file `%s'", 123},
  {"For help, run %s and type `help' at the prompt", 124},
  {"\
Useful commands:\n\
\thelp     to get some help\n\
\tquit     to quit\n", 125},
  {"usage: pybcompact <latexfile> <bibtexfiles...>", 126},
  {"pybcompact: error: %s\n", 127},
  {"no entry", 128},
  {"can't find the following entries: %s", 129},
  {"usage: pybconvert <source>..<target> <input> [output]", 130},
  {"pybconvert: bad conversion format", 131},
  {"usage: pybformat [bibtexfiles...]\n", 132},
  {"pybformat: error: %s\n", 133},
  {"pybformat: warning: %s\n", 134},
  {"can't find style `%s'", 135},
  {"usage: pybtex <latexfile> [bibtexfiles...]", 136},
  {"pybtex: error: %s\n", 137},
  {"pybtex: warning: the following keys were not resolved", 138},
  {"no style defined", 139},
};

int _msg_tbl_length = 139;
