/* Automatically generated by po2tbl.sed from pybliographer.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"warning: can't import %s: %s", 2},
  {"value of `%s' should be %s", 3},
  {"a String", 4},
  {"an Integer", 5},
  {"an Integer under %d", 6},
  {"an Integer over %d", 7},
  {"an Integer between %d and %d", 8},
  {"an Instance of `%s'", 9},
  {"a Tuple ([%s])", 10},
  {"a List (%s)", 11},
  {"a Dictionnary (%s, %s)", 12},
  {"Illegal year value", 13},
  {"Illegal month value", 14},
  {"Illegal day value", 15},
  {"in %s", 16},
  {"no input pipe `%s'", 17},
  {"no output pipe `%s'", 18},
  {"method `%s' provides no opener", 19},
  {"File `%s' does not exist", 20},
  {"don't know how to open `%s'", 21},
  {"method `%s' provides no iterator", 22},
  {"key `%s' is malformed", 23},
  {"%s:%d: key `%s' already defined", 24},
  {"Format entries", 25},
  {"Bibliography style:", 26},
  {"Select style", 27},
  {"Output format:", 28},
  {"Output File:", 29},
  {"Select output file", 30},
  {"Day", 31},
  {"Month", 32},
  {"Year", 33},
  {"Invalid day field in date", 34},
  {"Invalid month field in date", 35},
  {"Invalid year field in date", 36},
  {"Entry type", 37},
  {"Key", 38},
  {"Create Field", 39},
  {"Mandatory", 40},
  {"Optional", 41},
  {"Extra", 42},
  {"New text", 43},
  {"Invalid key format", 44},
  {"Key `%s' already exists", 45},
  {"Error in native string parsing", 46},
  {"Native Editing", 47},
  {"Standard Editing", 48},
  {"File", 49},
  {"Bibliography type:", 50},
  {"Add...", 51},
  {"Edit...", 52},
  {"Delete", 53},
  {"Search", 54},
  {"Field", 55},
  {"Pattern", 56},
  {"Simple Search", 57},
  {"Search command:", 58},
  {"Expert Search", 59},
  {"Full database", 60},
  {"internal error during evaluation", 61},
  {"\
while compiling %s\n\
error: %s", 62},
  {"Select sort criterions", 63},
  {"In use", 64},
  {"Sort criterions", 65},
  {"[Entry Type]", 66},
  {"[Key Value]", 67},
  {"Reorder", 68},
  {"Unselect all", 69},
  {"Yes", 70},
  {"\
The following errors occured:\n\
\n", 71},
  {"New", 72},
  {"Merge...", 73},
  {"Previous Documents", 74},
  {"About...", 75},
  {"Submit a Bug Report", 76},
  {"Sort...", 77},
  {"Cite", 78},
  {"Format...", 79},
  {"Edit", 80},
  {"Settings", 81},
  {"Help", 82},
  {"Open", 83},
  {"Save", 84},
  {"Find", 85},
  {"Close", 86},
  {"\
can't open file `%s' for writing:\n\
%s", 87},
  {"New database", 88},
  {"[no entry]", 89},
  {"[1 entry]", 90},
  {"[%d entries]", 91},
  {"[%d/1 entry]", 92},
  {"[%d/%d entries]", 93},
  {"[modified]", 94},
  {"\
The database has been modified.\n\
Discard changes ?", 95},
  {"Merge file", 96},
  {"Open error", 97},
  {"Merge status", 98},
  {"Open file", 99},
  {"\
Unable to save `%s':\n\
%s", 100},
  {"\
An internal error occured during saving\n\
Try to Save As...", 101},
  {"\
The file `%s' already exists.\n\
Overwrite it ?", 102},
  {"\
During opening:\n\
%s", 103},
  {"\
An entry called `%s' already exists.\n\
Rename and add it anyway ?", 104},
  {"Really remove all the entries ?", 105},
  {"Really edit %d entries ?", 106},
  {"Remove all the %d entries ?", 107},
  {"Remove entry `%s' ?", 108},
  {"\
Can't connect to LyX:\n\
%s", 109},
  {"\
Please install bug-buddy\n\
to use this feature", 110},
  {"This program is copyrighted under the GNU GPL", 111},
  {"Gnome interface to the Pybliographer system.", 112},
  {"Pybliographer Home Page", 113},
  {"This is %s, version %s", 114},
  {"This is free software with ABSOLUTELY NO WARRANTY.", 115},
  {"For details, type `warranty'.", 116},
  {"%s: error: can't open file `%s'", 117},
  {"For help, run %s and type `help' at the prompt", 118},
  {"\
Useful commands:\n\
\thelp     to get some help\n\
\tquit     to quit\n", 119},
  {"usage: pybcompact <latexfile> <bibtexfiles...>", 120},
  {"pybcompact: error: %s\n", 121},
  {"no entry", 122},
  {"can't find the following entries: %s", 123},
  {"usage: pybconvert <source>..<target> <input> [output]", 124},
  {"pybconvert: bad conversion format", 125},
  {"usage: pybformat [bibtexfiles...]\n", 126},
  {"pybformat: error: %s\n", 127},
  {"pybformat: warning: %s\n", 128},
  {"can't find style `%s'", 129},
  {"usage: pybtex <latexfile> [bibtexfiles...]", 130},
  {"pybtex: error: %s\n", 131},
  {"pybtex: warning: the following keys were not resolved", 132},
  {"no style defined", 133},
};

int _msg_tbl_length = 133;
